### ISSUE TITLE
https security problem on downloading data files

### ISSUE THREAD

**Issue by NoSyu** [KLUE-benchmark/KLUE#11]
안녕하세요.

문제) 

Tasks에 있는 데이터를 다운로드 받으려고 하니 https 보안 경고 메시지가 뜹니다.

예)

Page URL: https://klue-benchmark.com/tasks/66/data/download

File URL: https://klue-benchmark.com.s3.amazonaws.com/app/Competitions/000066/data/ynat-v1.tar.gz

Error message: 

```
웹 사이트는 인증서로 신원을 증명합니다. Firefox는 이 사이트가 klue-benchmark.com.s3.amazonaws.com에 대해 유효하지 않은 인증서를 사용하고 있기 때문에 신뢰하지 않습니다. 인증서는 다음의 이름에 대해서만 유효합니다: *.s3.amazonaws.com, s3.amazonaws.com
```

이러한 메시지는 구글 크롬에서도 발견됩니다.

제안하는 해결 방법)

https => http로 바꾸면 됩니다.

감사합니다.

**Comment by marble25** [comment]
@NoSyu 
안녕하세요. 
이슈 리포트 감사드립니다.

인증서 수정해서 https url로도 경고 메시지 없이 다운로드 받을 수 있도록 해결하겠습니다.
감사합니다.
