### ISSUE TITLE
한국어 웹페이지 제공 문의

### ISSUE THREAD

**Issue by hexists** [KLUE-benchmark/KLUE#12]
안녕하세요.
KLUE 프로젝트를 관심있게 보고 있습니다.
먼저 중요한 프로젝트를 진행하고 공개해주셔서 감사합니다.

한가지 제안이 있습니다.
'한국어' 벤치마크 셋인데, 모두 영어로 설명되어 있어 아쉽습니다^^;

https://klue-benchmark.com/, https://github.com/KLUE-benchmark/KLUE
웹페이지, 메뉴얼 등을 한국어도 함께 제공한다면 접근성이 향상될 것 같습니다.
긍정적인 검토 부탁드립니다~
감사합니다.

**Comment by SungjoonPark** [comment]
저희는 한국어 벤치마크를 한국 뿐만 아니라 좀 더 넓게 다른 나라 연구자들 또한 사용할 수 있도록 영어 버전을 우선적으로 준비했습니다. 한국어 버전의 웹페이지, 설명, 매뉴얼은 저희도 중요하게 생각하고 있습니다. 다만, 저희는 프로젝트 그룹이었던 만큼 저희가 직접 모든 부분을 준비해서 공개하기보다는, 한국어 버전의 페이지 번역과 같은 경우 컨트리뷰터 분들의 도움을 받고자 합니다. 문의주신 분께서 직접 기여해주시면 좋을 것 같습니다!

**Comment by hexists** [comment]
@SungjoonPark 
답변 주셔서 감사합니다.
한국어 버전도 공유하고 계시다니 기대하고 있겠습니다.
많은 컨트리뷰터가 함께 참여해서 더 좋은 방향으로 발전하길 기대하겠습니다.
