### ISSUE TITLE
test 데이터셋

### ISSUE THREAD

**Issue by 2eews** [KLUE-benchmark/KLUE#20]
test 데이터셋도 배포하실 예정인지 궁금합니다!
배포하신 다면 예정일은 언제인지도 알려주시면 감사하겠습니다

**Comment by SungjoonPark** [comment]
test 데이터셋은 배포예정이 없습니다. test set은 비공개이며, 리더보드 서브미션을 통해서만 접근하실 수 있습니다.

**Comment by 2eews** [comment]
감사합니다! 그리고 파인 튜닝 및 평가 스크립트는 언제 제공하실 예정인지 궁금합니다.

**Comment by inmoonlight** [comment]
파인 튜닝 및 평가 스크립트는 7월 말 공개 예정입니다!
