### ISSUE TITLE
ner train dataset 입력 오류

### ISSUE THREAD

**Issue by jw0831** [KLUE-benchmark/KLUE#21]
14137    <새정추:OG>는 <이날:DT> <여의도 신동해빌딩 :LC> 사무실에서 회의를 열고...
Name: sent_tag, dtype: object
14137    새정추는 이날 여의도 신동해빌딩  사무실에서 회의를 열고 이같이 결정했다고 새정추측...
Name: sentence, dtype: object

#<여의도 신동해빌딩 :LC> 스페이스가 잘못 들어있어요 <여의도 신동해빌딩:LC> 이렇게 붙어있어야 되네요

**Comment by inmoonlight** [comment]
@jw0831 제보 감사드립니다! 7월 말 파인튜닝 코드 공개 전에 데이터 이슈 주신 것들 반영해서 버전 업을 진행하려고 합니다 :)

**Comment by inmoonlight** [comment]
v1.1에 해당 이슈 반영완료했습니다. (cc. @daydrill )
