### ISSUE TITLE
klue-dp-v1 POS tag 오류

### ISSUE THREAD

**Issue by Sunkyoung** [KLUE-benchmark/KLUE#22]
klue-dp train dataset 에서 POS tag와 관련하여 typo error가 발견되어 이슈 남깁니다!
guid : klue-dp-v1_train_05871_airbnb 에서 4번째의 '힘들수도' 의 tag set AV+ETM+NNB+JX 에서 AV라는 tag가 tag list 중에 없어서 살펴보니 '힘들'에 알맞는 POS tag인 VA tag의 오타로 기입된 것 같습니다.

**Comment by inmoonlight** [comment]
note: 해당 이슈는 train/dev/test 전수에 대해서 조사해본 결과 train set 에만 나타나는 문제임을 확인하였고, v1.1에 반영하였습니다.
