### ISSUE TITLE
[YNAT] annotation protocol 질문

### ISSUE THREAD

**Issue by parkwonjae** [KLUE-benchmark/KLUE#28]
## Description
안녕하세요 
YNAT annotation protocol에 대해 질문이있습니다. 

annotator분들께 각 토픽의 key term와 headline만 제공되고, 뉴스 본문은 제공 안 한 상태로 annotation을 한 것인지 질문드립니다.

**Comment by songys** [comment]
annotator분들께는 각 토픽의 headline만 제공되었습니다.  키워드나 뉴스 본문은 제공되지 않았습니다. 다만, headline만 보고 토픽을 선택하기 어려운 경우는 1,2,3 순위로 다른 토픽을 선택할 수도 있었습니다. 물론 그래도 선택할 수 없는 경우는 패스할 수도 있습니다.  하지만 대부분 첫번째에서 토픽을 결정하셨던 것으로 기억합니다.
