### ISSUE TITLE
ynat-v1_test 데이터셋 오류

### ISSUE THREAD

**Issue by bzantium** [KLUE-benchmark/KLUE#3]
line 321에 "," 를 지워줘야 잘 작동합니다. (json파일형식에서 마지막 sample 뒤에 , 가 사용되어 발생하는 에러)

![image](https://user-images.githubusercontent.com/19511788/119934735-38f36280-bfc1-11eb-832e-f8e145053bde.png)

**Comment by inmoonlight** [comment]
@bzantium 

안녕하세요! 이슈 리포트 감사드립니다 ㅎㅎ 해당 내용 수정해서 새롭게 데이터 배포하는 중에 있습니다!

**Comment by inmoonlight** [comment]
수정된 버전으로 배포되었습니다. 추가적으로 `test.json` 이라는 파일명이 klue의 test 데이터로 착각할 우려가 있을 것 같아 `dev_sample_10.json` 이라는 이름으로 변경했습니다. 감사합니다.

**Comment by bzantium** [comment]
감사합니다!
