### ISSUE TITLE
[Leaderboard] 모델 무조건 공개 원칙 issue

### ISSUE THREAD

**Issue by Soonhwan-Kwon** [KLUE-benchmark/KLUE#30]
좋은 리더보드를 오픈해주셔서 감사합니다.

현재는 모델을 제출하면 무조건 공개를 원칙으로
진행되고 있는데요,
혹시 모델 다운로드 및 정보를 비공개 상태로 제출하는 기능을 추가하면 어떨까 싶습니다.

그 이유는
1. 모델 무조건 공개 원칙으로 인해 많은 회사/개인이 제출을 꺼릴 수 있으며,
2. 리더보드에 올라간 모델을 단순 다운로드하여 조금 고친 후 재제출하는 식의 의미없는 제출로 인한 리더보드 망가짐
이 우려됩니다.

감사합니다.

**Comment by inmoonlight** [comment]
안녕하세요, @Soonhwan-Kwon 님

1번과 같은 이유로 현재에도 모델 제출 이후 submission 된 내용을 공개할지 말지를 선택할 수 있는 옵션이 존재합니다. 
<img src="https://user-images.githubusercontent.com/24843996/128986011-1bf09c1a-86be-40e2-af90-72325c2d34db.png" width=70%>

2번과 같은 이유로 유의미하지 않은 모델이 업로드 될 가능성을 고려하여 모델 학습에 대한 내용을 누구나 확인할 수 있도록
public하게 제출된 모델의 경우 공개된 repository 혹은 model hub url을 첨부하는 내용을 고수하였습니다.

**Comment by Soonhwan-Kwon** [comment]
@inmoonlight 네 답변감사합니다. 다만 제가 언급드린건 본인 점수를 리더보드에 공개하면서도 private하게 모델을 숨길 수 있는 기능이며, 현재까지 어떠한 기업/개인이 쉽게 참여하지 못하는 이유가 해당 기능이 없기 때문이라 생각하여 건의드렸습니다.

**Comment by Soonhwan-Kwon** [comment]
업스테이지의 입장도 이해하고 있어 무리한 요구를
드리는 것 같아 해당 이슈는 close하겠습니다 답변 들려주셔서 감사합니다

**Comment by inmoonlight** [comment]
@Soonhwan-Kwon 넵 이해에 감사드립니다.
