### ISSUE TITLE
PLM 학습 및 KLUE에 활용된 Namuwiki 라이센스에 대해 궁금한 점이 있습니다.

### ISSUE THREAD

**Issue by P4RK-J4EWOONG** [KLUE-benchmark/KLUE#31]
안녕하세요.

너무 좋은 데이터와 모델을 공개해주셔서 너무 감사합니다!
KLUE의 데이터 및 모델을 활용하고 싶어서 알아보던 중에
데이터 및 공개해주신 PLM에 나무위키 덤프가 사용된 것을 알게되었습니다.

그런데 나무위키 데이터의 라이센스는

"이 저작물은 CC BY-NC-SA 2.0 KR에 따라 이용할 수 있습니다. (단, 라이선스가 명시된 일부 문서 및 삽화 제외)
기여하신 문서의 저작권은 각 기여자에게 있으며, 각 기여자는 기여하신 부분의 저작권을 갖습니다." 

이렇게 표기가 되어 있던데요, 
이럴 경우 이를 활용한 2차 저작물의 라이센스도 혹여나 영리적 목적으로 사용하기 힘든 것이 아닌지 걱정되어 문의드렸습니다.
혹시 이부분을 공정 이용으로 생각해서 영리적으로 사용할 수 있는 건지, 아니면 별도로 해결을 하신건지 여쭤보고 싶습니다.

**Comment by SungjoonPark** [comment]
벤치마크 train/dev/test 데이터에는 나무위키를 사용하지 않았으며, 사전학습에 사용된 코퍼스 또한 저희가 배포하지 않습니다 :)

**Comment by P4RK-J4EWOONG** [comment]
답변 감사합니다! 그렇다면 공개해주신 PLM 모델들도 CC-BY-SA 4.0 라이센스 하에 사용하면 될까요?

**Comment by inmoonlight** [comment]
모델은 현행 저작권법상 저작물로 간주되지 않습니다. 따라서 현재 허깅페이스에 업로드 된 모델 라이센스는 모델 학습 코드의 라이센스를 따르고 있고, 해당 라이센스 하에 사용해주시면 좋을 것 같습니다.

**Comment by P4RK-J4EWOONG** [comment]
답변 감사합니다.

라이센스에 대해 의문이 있었는데 속시원하게 해결되었습니다!

항상 좋은 자료들 공개해주셔서 감사합니다.
