### ISSUE TITLE
홈페이지 statistics typo

### ISSUE THREAD

**Issue by jungwhank** [KLUE-benchmark/KLUE#4]
안녕하세요,
우선 좋은 벤치마크를 제공해주셔서 감사합니다.

KLUE관련하여 Huggingface datasets [PR](https://github.com/huggingface/datasets/pull/2416)을 진행하다가, 홈페이지에서 오타 몇가지 발견하여 이슈 리포트 드립니다.

1. [NER 페이지](https://klue-benchmark.com/tasks/69/data/description)과 [RE 페이지](https://klue-benchmark.com/tasks/70/data/description) 첫번째 테이블 중복
2. [MRC 페이지](https://klue-benchmark.com/tasks/72/data/description) 첫번째 테이블 dev Questions 갯수 홈페이지(`5941`) vs paper(`5841` - Table 19)
3. MRC 페이지 두번째 테이블과 바로 밑 문장 statistics 차이 `12,207 | 7,895 | 9,211` vs `KLUE-MRC consists of 12,286 question paraphrasing, 7,931 multi-sentence reasoning and 9,269 unanswerable questions.` 

감사합니다.

**Comment by inmoonlight** [comment]
@jungwhank 

안녕하세요! 이슈 리포트 감사드립니다.

1. 이슈 확인했고, 수정 중에 있습니다
2. 페이퍼의 내용이 맞습니다 (5841)
3. 테이블 내용이 맞습니다. 페이퍼에도 수정해서 새로 업로드할 예정입니다. (12,207 | 7,895 | 9,211)

감사합니다!
